# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu, macos]
        ruby-version: ['3.2', '3.4']
        rails-version: ['7.1', '8.0.1']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        # bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Install Rails
      run: gem install rails --version ${{ matrix.rails-version }}
    - name: Setup a fake git email # Git is upset otherwise
      run: git config --global user.email "runner@github.com"
    - name: Setup a fake git name # Git is upset otherwise
      run: git config --global user.name "the GitHub Runner"
    - name: Start a test app
      run: rails new -T --minimal -m "./template.rb" -f foobar
    - name: Test the page
      run: cd foobar && bundle exec cucumber --publish-quiet
